import React, { useState, useEffect, useMemo } from 'react';
import { Send, FileCode, Edit3 } from 'lucide-react';
import { ApprovalWorkflow } from './ApprovalWorkflow';

interface RFQEditorProps {
  rfq: any;
  token: string | null;
  onApprove: (rfqId: string) => void;
  onSend: (rfqId: string) => void;
  onUpdate: (rfqId: string, title: string, content: string) => void;
  onStatusChange: (newStatus: string) => void;
  isSending: boolean;
}

/** Converts a Markdown string to safe HTML for display inside the RFQ viewer. */
function markdownToHtml(md: string): string {
  if (!md) return '';

  let html = md
    // Headings (### → h3, ## → h2, # → h1)
    .replace(/^### (.+)$/gm, '<h3 style="font-size:1rem;color:#a5b4fc;margin:1rem 0 0.3rem">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 style="font-size:1.1rem;color:#c4b5fd;margin:1.2rem 0 0.4rem">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 style="font-size:1.25rem;color:#f8fafc;margin:1.4rem 0 0.5rem">$1</h1>')

    // Horizontal rule
    .replace(/^---$/gm, '<hr style="border:none;border-top:1px solid rgba(255,255,255,0.1);margin:1rem 0"/>')

    // Bold + italic combinations
    .replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>')
    // Bold
    .replace(/\*\*(.+?)\*\*/g, '<strong style="color:#f8fafc">$1</strong>')
    // Italic
    .replace(/\*(.+?)\*/g, '<em>$1</em>')

    // Inline code
    .replace(/`(.+?)`/g, '<code style="background:rgba(139,92,246,0.2);color:#c4b5fd;padding:0.1rem 0.4rem;border-radius:4px;font-size:0.88em">$1</code>')

    // Bullet list items
    .replace(/^[\-\*] (.+)$/gm, '<li style="margin:0.2rem 0 0.2rem 1rem;list-style:disc">$1</li>')

    // Numbered list items
    .replace(/^\d+\. (.+)$/gm, '<li style="margin:0.2rem 0 0.2rem 1rem;list-style:decimal">$1</li>')

    // Wrap consecutive <li> in <ul>
    .replace(/((?:<li[^>]*>.*<\/li>\n?)+)/g, '<ul style="padding-left:1rem;margin:0.5rem 0">$1</ul>')

    // Double line-breaks → paragraph separators
    .replace(/\n{2,}/g, '<br/><br/>');

  return html;
}

export const RFQEditor: React.FC<RFQEditorProps> = ({
  rfq,
  token,
  onSend,
  onUpdate,
  onStatusChange,
  isSending,
}) => {
  if (!rfq) return null;

  const [title, setTitle] = useState(rfq.title || '');
  const [content, setContent] = useState(rfq.content || '');
  const [isEditing, setIsEditing] = useState(false);
  const [rfqStatus, setRfqStatus] = useState(rfq.status);

  useEffect(() => {
    if (rfq?.status) setRfqStatus(rfq.status);
  }, [rfq?.status]);

  useEffect(() => {
    setContent(rfq.content || '');
    setTitle(rfq.title || '');
  }, [rfq.id]);

  const renderedHtml = useMemo(() => markdownToHtml(content), [content]);

  const handleSave = () => {
    onUpdate(rfq.id, title, content);
    setIsEditing(false);
  };

  const handleStatusChange = (newStatus: string) => {
    setRfqStatus(newStatus);
    onStatusChange(newStatus);
  };

  const STATUS_LABEL_MAP: Record<string, string> = {
    draft: 'Draft',
    rfq_drafted: 'Draft',
    pending_approval: 'Pending Approval',
    approved: 'Approved',
    sent: 'Dispatched',
  };

  return (
    <div>
      {/* Multi-Approver Workflow Panel */}
      <ApprovalWorkflow
        rfq={rfq}
        token={token}
        onStatusChange={handleStatusChange}
      />

      {/* RFQ Document Card */}
      <div className="glass-card" style={{ padding: '2rem', marginBottom: '2rem' }}>
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: '1.5rem',
            flexWrap: 'wrap',
            gap: '1rem',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
            <div style={{ padding: '0.5rem', borderRadius: '8px', background: 'rgba(168, 85, 247, 0.15)', color: '#a855f7' }}>
              <FileCode size={24} />
            </div>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <h2 style={{ fontSize: '1.3rem', color: '#f8fafc' }}>{rfq.title}</h2>
                <span className={`badge badge-${rfqStatus}`}>
                  {STATUS_LABEL_MAP[rfqStatus] || rfqStatus} (v{rfq.version})
                </span>
              </div>
              <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>
                Generated by SourcePilot RFQ Generator Agent. Human review and multi-approver sign-off required prior to dispatch.
              </p>
            </div>
          </div>

          <div style={{ display: 'flex', gap: '0.75rem' }}>
            {isEditing ? (
              <button className="btn btn-secondary" onClick={handleSave}>Save Revision</button>
            ) : (
              <button className="btn btn-secondary" onClick={() => setIsEditing(true)}>
                <Edit3 size={16} /> Edit RFQ Text
              </button>
            )}

            {rfqStatus === 'approved' && (
              <button
                id="dispatch-rfq-btn"
                className="btn btn-primary anim-pulse"
                onClick={() => onSend(rfq.id)}
                disabled={isSending}
              >
                <Send size={18} /> {isSending ? 'Dispatching…' : 'Dispatch to Selected Suppliers'}
              </button>
            )}
          </div>
        </div>

        {isEditing ? (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <input
              className="form-input"
              value={title}
              onChange={e => setTitle(e.target.value)}
              placeholder="RFQ Title"
            />
            <textarea
              className="form-textarea"
              rows={18}
              value={content}
              onChange={e => setContent(e.target.value)}
              style={{ fontFamily: 'monospace', fontSize: '0.88rem', lineHeight: '1.55' }}
            />
          </div>
        ) : (
          <div
            style={{
              background: 'rgba(7, 10, 17, 0.7)',
              borderRadius: '12px',
              padding: '1.5rem 2rem',
              lineHeight: '1.7',
              color: '#e2e8f0',
              border: '1px solid rgba(255, 255, 255, 0.05)',
              fontSize: '0.95rem',
            }}
            dangerouslySetInnerHTML={{ __html: renderedHtml }}
          />
        )}
      </div>
    </div>
  );
};
