import React, { useState } from 'react';
import { Send, CheckCircle, FileCode, Edit3, Eye, Sparkles } from 'lucide-react';

interface RFQEditorProps {
  rfq: any;
  onApprove: (rfqId: string) => void;
  onSend: (rfqId: string) => void;
  onUpdate: (rfqId: string, title: string, content: string) => void;
  isSending: boolean;
}

export const RFQEditor: React.FC<RFQEditorProps> = ({ rfq, onApprove, onSend, onUpdate, isSending }) => {
  if (!rfq) return null;

  const [title, setTitle] = useState(rfq.title || '');
  const [content, setContent] = useState(rfq.content || '');
  const [isEditing, setIsEditing] = useState(false);

  const handleSave = () => {
    onUpdate(rfq.id, title, content);
    setIsEditing(false);
  };

  return (
    <div className="glass-card" style={{ padding: '2rem', marginBottom: '2rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '1rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <div style={{ padding: '0.5rem', borderRadius: '8px', background: 'rgba(168, 85, 247, 0.15)', color: '#a855f7' }}>
            <FileCode size={24} />
          </div>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
              <h2 style={{ fontSize: '1.3rem', color: '#f8fafc' }}>{rfq.title}</h2>
              <span className={`badge badge-${rfq.status}`}>Status: {rfq.status} (v{rfq.version})</span>
            </div>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>
              Generated by SourcePilot RFQ Generator Agent. Human review required prior to email dispatch.
            </p>
          </div>
        </div>

        <div style={{ display: 'flex', gap: '0.75rem' }}>
          {isEditing ? (
            <button className="btn btn-secondary" onClick={handleSave}>Save Revision</button>
          ) : (
            <button className="btn btn-secondary" onClick={() => setIsEditing(true)}>
              <Edit3 size={16} /> Edit RFQ Text
            </button>
          )}

          {rfq.status === 'draft' && (
            <button className="btn btn-emerald" onClick={() => onApprove(rfq.id)}>
              <CheckCircle size={18} /> Approve RFQ
            </button>
          )}

          {rfq.status === 'approved' && (
            <button className="btn btn-primary anim-pulse" onClick={() => onSend(rfq.id)} disabled={isSending}>
              <Send size={18} /> {isSending ? 'Dispatching...' : 'Dispatch to Selected Suppliers'}
            </button>
          )}
        </div>
      </div>

      {isEditing ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <input
            className="form-input"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="RFQ Title"
          />
          <textarea
            className="form-textarea"
            rows={14}
            value={content}
            onChange={(e) => setContent(e.target.value)}
            style={{ fontFamily: 'monospace', fontSize: '0.9rem' }}
          />
        </div>
      ) : (
        <div
          className="glass-card"
          style={{
            padding: '1.5rem',
            background: 'rgba(7, 10, 17, 0.7)',
            whiteSpace: 'pre-wrap',
            fontFamily: 'Inter, sans-serif',
            lineHeight: '1.6',
            color: '#e2e8f0',
            border: '1px solid rgba(255, 255, 255, 0.05)'
          }}
        >
          {rfq.content}
        </div>
      )}
    </div>
  );
};
